version: '3.4'

services:
  noteapi:
    image: ${DOCKER_REGISTRY-}noteapi
    build:
      context: .
      dockerfile: NoteApi/Dockerfile
    ports:
      - "5001:80"
  authapi:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    ports:
      - "5002:80"